name: Push book changes to BlueOS
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: blueos-push-${{ github.repository }}
  cancel-in-progress: false
jobs:
  push:
    if: ${{ vars.JOSH_SYNC_ENABLED == 'true' }}
    uses: vivoblueos-lab/josh-sync/.github/workflows/blueos-push.yml@e77018a508c975d103ff76acb18ef3ac5151d399
    with:
      github-app-client-id: ${{ vars.JOSH_SYNC_APP_CLIENT_ID }}
      pr-author: "blueos-lab-josh-sync[bot]"
      josh-sync-repository: vivoblueos-lab/josh-sync
      josh-sync-revision: e77018a508c975d103ff76acb18ef3ac5151d399
    secrets:
      github-app-secret: ${{ secrets.JOSH_SYNC_APP_PRIVATE_KEY }}
      approval-user-token: ${{ secrets.JOSH_SYNC_APPROVAL_USER_TOKEN }}
      approval-unsubscribe-user-token: ${{ secrets.JOSH_SYNC_APPROVAL_UNSUBSCRIBE_USER_TOKEN }}
